AWSTemplateFormatVersion: '2010-09-09'
Description: 'Setup Lambda function with S3 trigger.'

Resources:
  LambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: [lambda.amazonaws.com]
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Policies:
        - PolicyName: LambdaS3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                Resource: !Sub 'arn:aws:s3:::${RawDataBucket}/*'
              - Effect: Allow
                Action:
                  - 's3:PutObject'
                Resource: !Sub 'arn:aws:s3:::${DestinationBucket}/*'

  LambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: !Sub '${AWS::StackName}-CopyObject'
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn # This indicates the function depends on the IAM role. The creation orderis automatic
      Runtime: python3.12
      Timeout: 15
      Code:
        ZipFile: |
          import boto3
          import os
          import json
          def handler(event, context):
            s3 = boto3.client('s3')
            print("Received event data format: " + json.dumps(event))
            for record in event['Records']:
                source_bucket = record[0]['s3']['bucket']['name']
                source_file = record[0]['s3']['object']['key']
                destination_bucket = os.environ['DESTINATION_BUCKET']
                destination_file = 'data/' + source_file.split('/')[-1]
                s3.copy_object(Bucket=destination_bucket, CopySource={'Bucket': source_bucket, 'Key': source_file}, Key=destination_file)
      Environment:
        Variables:
          DESTINATION_BUCKET: !Ref DestinationBucket
          SOURCE_BUCKET: !Ref RawDataBucket

  LambdaPermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName: !Ref LambdaFunction
      Action: "lambda:InvokeFunction"
      Principal: "s3.amazonaws.com"
      SourceArn: !Sub 'arn:aws:s3:::${RawDataBucket}'

  S3BucketNotification:
    Type: 'AWS::S3::BucketNotification'
    Properties:
      Bucket: !Ref RawDataBucket
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: 's3:ObjectCreated:*'
            Function: !GetAtt LambdaFunction.Arn

Parameters:
  RawDataBucket:
    Type: String
    Description: Name for Raw Data S3 bucket
    Default: imba-rawdata

  DestinationBucket:
    Type: String
    Description: Name of Destination S3 bucket
    Default: imba-stanley

Outputs:
  LambdaFunctionName:
    Description: 'Name of the Lambda function'
    Value: !Ref LambdaFunction
