AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for S3 buckets and Lambda function setup for object copying.'

Parameters:
  RawDataBucketName:
    Type: String
    Description: Name for the raw data S3 bucket
    Default: imba-rawdata

  DestinationBucketName:
    Type: String
    Description: Name for the imba-stanley S3 bucket
    Default: imba-stanley


Conditions:
  ShouldCreateRawDataBucket: !Not [!Equals [!Ref RawDataBucketName, 'imba-rawdata']]
  ShouldCreateImbaStanleyBucket: !Not [!Equals [!Ref DestinationBucketName, 'imba-stanley']]

Resources:
  RawDataBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref RawDataBucketName
    DeletionPolicy: Retain

  ImbaStanleyBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref DestinationBucketName
    DeletionPolicy: Retain

  ScriptsBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub '${DestinationBucketName}-scripts'
    DeletionPolicy: Retain
 
Outputs:
  RawDataBucketName:
    Description: 'Name of the raw data S3 bucket'
    Value: !Ref RawDataBucketName
  DestinationBucketName:
    Description: 'Name of the imba-stanley S3 bucket'
    Value: !Ref DestinationBucketName
  ScriptsBucketName:
    Description: 'Name of the Glue scripts S3 bucket'
    Value: !Ref ScriptsBucket

