AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for S3 buckets and Lambda function setup for object copying.'

Parameters:
  RawDataBucketName:
    Type: String
    Description: Name for the raw data S3 bucket
    Default: imba-rawdata

  ImbaStanleyBucketName:
    Type: String
    Description: Name for the imba-stanley S3 bucket
    Default: imba-stanley

Resources:
  RawDataBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref RawDataBucketName

  ImbaStanleyBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref ImbaStanleyBucketName

  GlueScriptsBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub '${ImbaStanleyBucketName}-glue-scripts'
 
Outputs:
  RawDataBucketName:
    Description: 'Name of the raw data S3 bucket'
    Value: !Ref RawDataBucket
  ImbaStanleyBucketName:
    Description: 'Name of the imba-stanley S3 bucket'
    Value: !Ref ImbaStanleyBucket
  GlueScriptsBucketName:
    Description: 'Name of the Glue scripts S3 bucket'
    Value: !Ref GlueScriptsBucket

