name: Deploy AWS Resources

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  
#  workflow_dispatch: # Trigger manually on workflow

jobs:
  deploy_resources:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Conditional deployment based on changes in main.yml
      # CloudFormation deployment step will execute only if the relevant files have changed
      # By using glue/**/*.py, it means "include any Python script located in the glue directory or any of its subdirectories
      - name: Detect Changes
        id: changes
        uses: dorny/paths-filter@v2
        with:
          list-files: shell
          filters: |
            s3:
             - 'cfn/s3.yml'
            lambda:
              - 'cfn/lambda.yml'
            glue:
              - 'cfn/glue.yml'
              - 'glue/**/*.py'
      

      - name: Check Current S3 Stack Template
        id: s3-stack-check
        run: |
          if aws cloudformation describe-stacks --stack-name imba-RawDataBucket &>/dev/null; then
            TEMPLATE_BODY=$(cat cfn/s3.yml | base64 -w 0)
            STACK_TEMPLATE=$(aws cloudformation get-template --stack-name imba-RawDataBucket --query 'TemplateBody' --output text | base64 -w 0)
            if [ "$TEMPLATE_BODY" = "$STACK_TEMPLATE" ]; then
              echo "s3_stack_up_to_date=true" >> $GITHUB_OUTPUT
            else
              echo "s3_stack_up_to_date=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "s3_stack_up_to_date=false" >> $GITHUB_OUTPUT
          fi
        shell: bash
      
      - name: Deploy S3 Buckets CloudFormation Stack
        id: s3-buckets
        if: steps.changes.outputs.s3 == 'true' || steps.s3-stack-check.outputs.s3_stack_up_to_date != 'true'
        uses: aws-actions/aws-cloudformation-github-deploy@v1.0.4
        with:
          name: imba-RawDataBucket
          template: cfn/s3.yml
          capabilities: CAPABILITY_IAM

      - name: Set S3 Bucket Outputs
        run: |
          RAW_DATA_BUCKET_NAME=$(aws cloudformation describe-stacks --stack-name imba-RawDataBucket --query "Stacks[0].Outputs[?OutputKey=='RawDataBucketName'].OutputValue" --output text)
          IMBA_STANLEY_BUCKET_NAME=$(aws cloudformation describe-stacks --stack-name imba-RawDataBucket --query "Stacks[0].Outputs[?OutputKey=='ImbaStanleyBucketName'].OutputValue" --output text)
          GLUE_SCRIPTS_BUCKET_NAME=$(aws cloudformation describe-stacks --stack-name imba-RawDataBucket --query "Stacks[0].Outputs[?OutputKey=='GlueScriptsBucketName'].OutputValue" --output text)
          echo "RAW_DATA_BUCKET_NAME=$RAW_DATA_BUCKET_NAME" >> $GITHUB_ENV
          echo "IMBA_STANLEY_BUCKET_NAME=$IMBA_STANLEY_BUCKET_NAME" >> $GITHUB_ENV
          echo "GLUE_SCRIPTS_BUCKET_NAME=$GLUE_SCRIPTS_BUCKET_NAME" >> $GITHUB_ENV
        shell: bash
   


      - name: Check Current Lambda Stack Template
        id: lambda-stack-check
        run: |
          if aws cloudformation describe-stacks --stack-name imba-LambdaFunction &>/dev/null; then
            TEMPLATE_BODY=$(cat cfn/lambda.yml | base64 -w 0)
            STACK_TEMPLATE=$(aws cloudformation get-template --stack-name imba-LambdaFunction --query 'TemplateBody' --output text | base64 -w 0)
            if [ "$TEMPLATE_BODY" = "$STACK_TEMPLATE" ]; then
              echo "lambda_stack_up_to_date=true" >> $GITHUB_OUTPUT
            else
              echo "lambda_stack_up_to_date=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "lambda_stack_up_to_date=false" >> $GITHUB_OUTPUT
          fi
        shell: bash
      
      
      - name: Deploy Lambda Function CloudFormation Stack
        id: lambda-function
        if: steps.changes.outputs.lambda == 'true' || steps.lambda-stack-check.outputs.lambda_stack_up_to_date != 'true'
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: imba-LambdaFunction
          template: cfn/lambda.yml
          capabilities: CAPABILITY_IAM

      - name: Fetch Lambda Function ARN
        run: |
          LAMBDA_FUNCTION_ARN=$(aws cloudformation describe-stacks --stack-name imba-LambdaFunction --query "Stacks[0].Outputs[?OutputKey=='LambdaFunctionArn'].OutputValue" --output text)
          echo "LAMBDA_FUNCTION_ARN=$LAMBDA_FUNCTION_ARN" >> $GITHUB_ENV

      # refer to AWS CLI Command Reference https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3api/put-bucket-notification-configuration.html
      - name: Set S3 Bucket Notification
        run: |
          aws s3api put-bucket-notification-configuration \
            --bucket ${{ env.RAW_DATA_BUCKET_NAME }} \
            --notification-configuration '{
              "LambdaFunctionConfigurations": [
                {
                  "LambdaFunctionArn": "${{ env.LAMBDA_FUNCTION_ARN }}",
                  "Events": ["s3:ObjectCreated:*"]
                }
              ]
            }'
      


      - name: Check Current Glue Stack Template
        id: glue-stack-check
        run: |
          if aws cloudformation describe-stacks --stack-name imba-GlueJob &>/dev/null; then
            TEMPLATE_BODY=$(cat cfn/glue.yml | base64 -w 0)
            STACK_TEMPLATE=$(aws cloudformation get-template --stack-name imba-GlueJob --query 'TemplateBody' --output text | base64 -w 0)
            if [ "$TEMPLATE_BODY" = "$STACK_TEMPLATE" ]; then
              echo "glue_stack_up_to_date=true" >> $GITHUB_OUTPUT
            else
              echo "glue_stack_up_to_date=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "glue_stack_up_to_date=false" >> $GITHUB_OUTPUT
          fi
          echo "glue_stack_exists=$(aws cloudformation describe-stacks --stack-name imba-GlueJob &>/dev/null && echo 'true' || echo 'false')" >> $GITHUB_OUTPUT
        shell: bash

      - name: Upload Glue Job Script
        if: steps.changes.outputs.glue == 'true' || steps.glue-stack-check.outputs.glue_stack_up_to_date != 'true'
        run: |
          aws s3 cp glue/etl_script.py s3://${{ env.GLUE_SCRIPTS_BUCKET_NAME }}/etl_script.py
        shell: bash


      - name: Deploy Glue Job CloudFormation Stack
        id: glue-job
        if: steps.changes.outputs.glue == 'true' || steps.glue-stack-check.outputs.glue_stack_up_to_date != 'true'
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: imba-GlueJob
          template: cfn/glue.yml
          parameter-overrides: >-
            GlueScriptsBucketName=${{ env.GLUE_SCRIPTS_BUCKET_NAME }},
            ImbaStanleyBucketName=${{ env.IMBA_STANLEY_BUCKET_NAME }}

      - name: Fetch Glue Job Name
        if: steps.glue-stack-check.outputs.glue_stack_exists == 'true'
        run: |
          GLUE_JOB_NAME=$(aws cloudformation describe-stacks --stack-name imba-GlueJob --query "Stacks[0].Outputs[?OutputKey=='GlueJobName'].OutputValue" --output text)
          echo "GLUE_JOB_NAME=$GLUE_JOB_NAME" >> $GITHUB_ENV