name: Deploy AWS Resources

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy_resources:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy S3 Buckets CloudFormation Stack
        id: s3-buckets
        uses: aws-actions/aws-cloudformation-github-deploy@v1.0.4
        with:
          name: imba-RawDataBucket
          template: cfn/s3.yml
          capabilities: CAPABILITY_IAM

      - name: Set S3 Bucket Output
        run: |
          RAW_DATA_BUCKET_NAME=$(aws cloudformation describe-stacks --stack-name imba-RawDataBucket --query "Stacks[0].Outputs[?OutputKey=='RawDataBucketName'].OutputValue" --output text)
          echo "RAW_DATA_BUCKET_NAME=$RAW_DATA_BUCKET_NAME" >> $GITHUB_ENV

      - name: Deploy Lambda Function CloudFormation Stack
        id: lambda-function
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: imba-LambdaFunction
          template: cfn/lambda.yml
          capabilities: CAPABILITY_IAM

      - name: Fetch Lambda Function ARN
        run: |
          LAMBDA_FUNCTION_ARN=$(aws cloudformation describe-stacks --stack-name imba-LambdaFunction --query "Stacks[0].Outputs[?OutputKey=='LambdaFunctionArn'].OutputValue" --output text)
          echo "LAMBDA_FUNCTION_ARN=$LAMBDA_FUNCTION_ARN" >> $GITHUB_ENV

      - name: Set S3 Bucket Notification
        run: |
          aws s3api put-bucket-notification-configuration \
            --bucket ${{ env.RAW_DATA_BUCKET_NAME }} \
            --notification-configuration '{
              "LambdaFunctionConfigurations": [
                {
                  "LambdaFunctionArn": "${{ env.LAMBDA_FUNCTION_ARN }}",
                  "Events": ["s3:ObjectCreated:*"]
                }
              ]
            }'

      - name: Debug Outputs
        run: |
          echo "Bucket Name: ${{ env.RAW_DATA_BUCKET_NAME }}"
          echo "Lambda ARN: ${{ env.LAMBDA_FUNCTION_ARN }}"
